env:
  browser: true
  es2021: true
  node: true
extends:
  - prettier
  - next/core-web-vitals
  - plugin:react-hooks/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - typescript
